<style>
    #pm-list-ddns-table thead tr th:first-child,
    #pm-list-ddns-table tbody tr td:first-child {
        width: 3em;
        min-width: 3em;
        max-width: 3em;
        word-break: break-all;
    }
    #pm-list-ddns-table tbody tr td:first-child {
        text-align: center;
    }
</style>
Dynamic DNS can only be added to existing records. If you want to add a record, please do this via the DNS view of your domain.
<?php
echo $this->renderList($this->records);
?>